apollo/manage/messages.py
the playback function, prior to this, used the specified URL to inject
messages. this would require the user to know the path to the Kannel
view. this commit fixes that.
=> fix: use correct URL for message playback

apollo/manage/messages.py
this commit fixes message playback by using the full URL to the Kannel
view instead of the passed-in URL for message injection
=> fix: use correct full URL to inject messages

apollo/submissions/filters.py
This PR sets the default quarantine status to None so only records that are not quarantined are displayed by default.
=> default filter value for quarantine status should be None

apollo/frontend/templates/frontend/submission_edit.html
This PR resolves #196 and makes the cancel button also return to the calling page with all query strings preserved.
=> fix: cancel button to navigate to referring page

apollo/frontend/templates/frontend/submission_edit.html, apollo/participants/views_participants.py
this PR makes the following changes:
- the view for verifying phone numbers now toggles between verified and not verified,
but the UI has not been updated, only the back end code (partial fix for #311)
- when a phone number is edited, the changes only affect the specific participant
it was changed for (see #302)
- when a phone number is edited, it is set as the primary phone number (see #301)
=> updates to phone number handling

apollo/locations/tasks.py
pandas uses numpy dtypes, which don't inherit from basic Python types
like int or float. this commit fixes the check to convert the location
code into a string.
see: #335
=> fix: stringify location code properly

apollo/frontend/templates/frontend/message_list.html
this commit fixes the error raised when the language is set to
other than English and the message log is viewed. the error is
raised by attempting to translate a string marked as a deferred
translated string
see: #350
=> fix: don't translate translated strings

apollo/locations/models.py, apollo/locations/utils.py
this commit works around NetworkX's failure (by design?)
to generate a proper shortest path when edges are unordered.
see: #334
=> fix: clear existing paths when creating paths

apollo/odk/views_odk.py
Some ODK clients like ODK collect do not return cookies that are sent to them and this makes it impossible for Apollo to retrieve the corresponding server-generated nonce and opaque values for Digest authentication. Considering that all communication happens over HTTPS, it is okay to skip validation of the nonce and opaque values which are there to prevent replay attacks.
=> skip validation of nonce and opaque values

Dockerfile
This PR switches the Apollo image from using the alpine linux variant of the python 3 base image to the default which is debian based. Initial decision to use alpine linux was to make compact images but the lack of glibc support has made this choice an unfavoured one.
Resolves #392
=> switch from alpine linux to the mainstream python docker image. #392

apollo/submissions/filters.py
when filtering an incident form by a choice option, explicitly
cast the database value to an integer
see: #395
=> fix: use explicit type casts

apollo/frontend/views_dashboard.py, apollo/process_analysis/views_process.py, apollo/result_analysis/views_results.py
- when conflicts are tracked, use location checklists as the data source for dashboard and data summaries
- when conflicts are not tracked, use participant checklists as the data source
- incidents are unaffected
=> change data source when conflicts are not tracked

apollo/__init__.py
removes the warning about the OpenAPI version when running the web process
=> chore: remove OpenAPI version warning

apollo/participants/views_participants.py, apollo/submissions/views_submissions.py
casting location/participant IDs as integer can cause strange errors,
as can be seen in the original comment on #361. this also would avoid
errors in the event that either kind of ID is not a numeric string
see: #361
=> fix: don't cast codes as integer

migrations/versions/872591ee58b4_.py
fixes an error running migrations on a fresh database.
=> fix: replace duplicate role ID

apollo/locations/tasks.py, apollo/participants/tasks.py, apollo/submissions/views_submissions.py
- this commit fixes a bug where Apollo would crash when attempting to sort a submission list (QA  or regular) by the participant name.
- this commit further strips prepending and successive whitespace from location and participant names on import
=> fix: use correct table names for sorting

apollo/participants/filters.py
this commit removes the extra location table join on participant sample
filters
=> fix: no location join on participant sample filter

apollo/frontend/helpers.py
this commit restricts analysis admin divisions to those contained in the target location's set
=> fix: limit selection by location set

apollo/locations/tasks.py
speeds up closure generation by limiting selected
paths to those for the current location set
=> chore: limit location type paths to current set

apollo/submissions/forms.py, apollo/submissions/views_submissions.py
some fields (`verified_fields` and `quarantine_status`, specifically)
are rendered in the submission edit only if you have a certain permission.
prior to this commit, editing submissions without that permission resulted
in a server error. this commit allows users lacking the permission to still
edit submissions without issues.
see: #623
=> fix: require same permissions to update conditional fields

apollo/frontend/filters.py, apollo/messaging/filters.py, apollo/submissions/filters.py
This PR resolves #594 by properly converting dates from the timezone configured for the application to UTC before using the value to filter records in the database (considering that the database timestamps are stored in UTC).
=> fixed timezone conversion for use in filters with a date widget

apollo/submissions/filters.py
this commit fixes an error that occurs when a user attempts to
filter the process data summary using a sample
=> fix: clear error on filtering process data summary by sample

apollo/participants/models.py, apollo/participants/services.py
for both import and exports, the following names are now used:
- "Participant ID" instead of "ID"
- "Location code" instead of "Location ID"
-  "Supervisor ID" instead of "Supervisor"
=> chore: standardize names across participant I/O

apollo/frontend/templates/frontend/participant_list.html, apollo/templates/admin/participant_list.html
this commit fixes nditech/apollo-issues#65 by
adding the request query parameters to the export URL
in the template
=> fix: add query parameters to export URL

apollo/submissions/views_submissions.py
this commit fixes nditech/apollo-issues#66 by limiting the
checklist selection to the current event.
see: nditech/apollo-issues#66
=> fix: limit submissions to current event
