nditech/apollo

Pipfile.lock

This PR fixes the package hashes so the appropriate version is installed when building the project.

update package hashes

---

apollo/constants.py
apollo/frontend/views_admin.py
apollo/frontend/views_users.py

this commit seeks to simplify locale selection by:
- removing the invalid choice of None from the list of other locales
- adding help text on selection/deselection of other locales
see #242

fix: simplify locale selection

---

apollo/frontend/helpers.py
apollo/frontend/templates/frontend/location_builder.html

Potential fix for #274 and #275

if a deployment is not found with localhost, retrieve the first one

---

apollo/frontend/templates/frontend/macros/submission_list_macros.html
apollo/frontend/templates/frontend/submission_edit.html
apollo/static/css/custom.css

This PR implements some bug fixes and a feature to indicate comments for checklists.

checklist updates

---

apollo/frontend/templates/frontend/macros/submission_list_macros.html
apollo/frontend/templates/frontend/submission_edit.html
apollo/frontend/templates/frontend/submission_list.html

* abbreviations for group names
* updated labels for export dropdown
* cosmetic fixes for the flag for QA in the checklist edit screen

fixes for the checklists

---

apollo/frontend/templates/frontend/dashboard.html
apollo/frontend/views_dashboard.py
apollo/submissions/filters.py

this PR adds the dashboard filter from 2.X to the 3.X dashboard (#305)

add dashboard filter

---

apollo/core.py
apollo/frontend/templates/frontend/macros/submission_list_filter.html
apollo/submissions/filters.py

This PR introduces the usage of a toggle control for optional inclusion of text group filters.

ui optional inclusion toggle

---

apollo/frontend/templates/frontend/dashboard.html
apollo/frontend/templates/frontend/layout.html
apollo/frontend/templates/frontend/macros/dashboard_filter.html
apollo/frontend/templates/frontend/macros/submission_list_filter.html
apollo/frontend/templates/frontend/macros/submission_list_macros.html
apollo/frontend/templates/frontend/submission_list.html
apollo/frontend/views_dashboard.py
apollo/static/js/dashboard.js
apollo/submissions/filters.py
apollo/submissions/views_submissions.py

Dashboard UI update

---

apollo/locations/tasks.py
apollo/locations/views_locations.py

this commit fixes issues with importing from Excel files
by opening all import files in binary mode
see #314

fix: open import files in binary mode

---

apollo/frontend/views_admin.py

feat: add name filtering for sets

---

apollo/frontend/dashboard.py

fix: compute dashboard statistics properly

---

apollo/frontend/dashboard.py

This reverts commit a42d5c4f2683bbbcfc7423a96d52843c9207d1e2.

Revert "fix: compute dashboard statistics properly (#336)"

---

apollo/frontend/dashboard.py

fixes issues with dashboard stats

---

apollo/frontend/filters.py
apollo/submissions/models.py

fix: remove 'REJECTED' for condition in QA filter

---

apollo/formsframework/models.py

create a form group if none was explicitly created.

feat: create default group if none exists

---

apollo/formsframework/models.py
apollo/frontend/templates/frontend/xformslist.xml
apollo/odk/views_odk.py

this commit reintegrates some of the functionality from #88
see: #344

fix: fix broken queries in ODK views

---

apollo/participants/tasks.py
apollo/participants/views_participants.py

also, use the ```numbers.Number``` abstract base class for column type checks
see: #361

fix: allow Excel file uploads for participants

---

apollo/dal/models.py

addresses #341 (and #353, as both process and results summaries were affected)

fix error on summary view

---

apollo/locations/views_locations.py
apollo/messaging/views_messages.py
apollo/participants/views_participants.py
apollo/submissions/views_submissions.py

fix: fix paging error on checklists/incidents

---

apollo/formsframework/models.py
apollo/submissions/__init__.py
apollo/submissions/views_submissions.py

also load comments directly from submission
fixes #44

fix: set deployment when creating submission comments

---

apollo/formsframework/models.py

this mirrors the functionality that was added for v2.

fix: add default group if none was created in form builder

---

apollo/frontend/templates/frontend/submission_edit.html

This PR allows the user to know early enough if there are (and how many) comments for that checklist.

show comments indicator early within the checklist

---

apollo/locations/tasks.py

fix: ignore location coordinates if invalid

---

apollo/locations/tasks.py

fix: allow equatorial coordinates in location uploads

---

apollo/submissions/views_submissions.py

fix: allow removal of critical incident fields

---

apollo/messaging/tasks.py
apollo/submissions/views_submissions.py

fix errors sending messages

---

apollo/odk/views_odk.py
apollo/submissions/forms.py

fix: enable overwrite by data submitted via ODK

---

apollo/frontend/templates/frontend/macros/submission_field_macros.html
apollo/frontend/templates/frontend/submission_edit.html
apollo/submissions/forms.py

this was under #253 and addresses #179

feat: use radio buttons for single-choice questions

---

apollo/frontend/templates/frontend/macros/submission_field_macros.html
apollo/frontend/templates/frontend/submission_edit.html
apollo/process_analysis/views_process.py
apollo/static/js/angular-form-builder.js
apollo/submissions/forms.py
apollo/submissions/models.py
apollo/templates/admin/formbuilder.html

several bug fixes

---

apollo/frontend/templates/frontend/message_list.html
apollo/messaging/services.py
apollo/messaging/views_messages.py
apollo/odk/utils.py
apollo/odk/views_odk.py

Log ODK submissions in message log

---

apollo/frontend/templates/frontend/submission_edit.html
apollo/submissions/models.py

restore the quarantine feature

---

apollo/formsframework/forms.py
apollo/formsframework/views_forms.py
apollo/result_analysis/views_results.py
apollo/submissions/filters.py
apollo/templates/admin/form_create.html
apollo/templates/admin/form_edit.html

adds a typo fix, changes the default filter option for incidents summary to "Confirmed" and updates the record selection algorithm for checklist summaries.

data summary updates

---

apollo/submissions/filters.py

feat: add extra quarantine filter options

---

apollo/frontend/views_dashboard.py

this commit fixes an error that occurs when a deployment is created

fix: render dashboard with no forms set up

---

apollo/frontend/templates/frontend/macros/quality_assurance_list_macros.html
apollo/frontend/templates/frontend/macros/submission_list_macros.html
apollo/frontend/templates/frontend/participant_list.html
apollo/frontend/templates/frontend/submission_edit.html
apollo/submissions/views_submissions.py

critical incidents now carry their unique ids and are displayed in the checklist and on the list of critical incidents.

resolves issues relating to the display of critical incidents

---

apollo/templates/admin/locations_list_filter.html

fix: remove error when rendering location filter

---

apollo/process_analysis/common.py
apollo/submissions/aggregation.py

feat: enhance aggregated export

---

apollo/formsframework/utils.py
apollo/formsframework/views_forms.py
apollo/locations/services.py
apollo/participants/services.py
apollo/submissions/aggregation.py
apollo/submissions/qa/query_builder.py
apollo/submissions/services.py
apollo/templates/admin/form_create.html

- fixes QA dashboard crash
- handle legacy form import
- fixes crashes on exporting empty data sets
- fixes crash on creating form

misc fixes

---

apollo/frontend/views_admin.py

fix: set deployment in role creation

---

apollo/static/js/angular-form-builder.js
apollo/static/js/locations_builder.js
apollo/templates/admin/formbuilder.html

This PR adds warnings when navigating away from the admin divisions or form builder after changes have been made.

added navigational warnings for a few more screens

---

apollo/locations/tasks.py
apollo/participants/tasks.py

fix: weed out invalid participant IDs on import

---

apollo/participants/views_participants.py
apollo/submissions/views_submissions.py

this commit resolves the issue with participants not being displayed
when multiple languages are enabled for a deployment.
see #528

fix: resolve issues with participant names

---

apollo/participants/services.py
apollo/participants/views_participants.py

fix: limit participant export to selected set

---

apollo/submissions/views_submissions.py

fix: render participants

---

apollo/messaging/services.py
apollo/submissions/views_submissions.py

fix: allow 0 in checklist submission edits

---

apollo/frontend/helpers.py
apollo/locations/models.py
apollo/locations/services.py
apollo/locations/utils.py

In:
- import form
- divisions export
- locations export

fix: forces sorting of locations and divisions

---

apollo/submissions/views_submissions.py

fix: limit QA to current event

---

apollo/locations/services.py

feat: include coordinates in location export

---

apollo/frontend/dashboard.py
apollo/frontend/templates/frontend/dashboard.html
apollo/frontend/templates/frontend/macros/submission_list_filter.html
apollo/frontend/templates/frontend/submission_list.html
apollo/frontend/views_dashboard.py
apollo/static/js/dashboard.js
apollo/templates/admin/form_create.html
apollo/templates/admin/form_edit.html

This PR adds support for displaying daily progress charts

survey dashboard and other fixes

---

apollo/frontend/views_dashboard.py

fixes an error visiting the dashboard when no forms are defined

fix: add check for event form

---

apollo/frontend/filters.py
apollo/submissions/views_submissions.py

this PR fixes a bug that appears when the QA list is filtered by a sample

fix: resolve bug when QA is filtered by sample

---

apollo/frontend/views_dashboard.py
apollo/locations/api/views.py
apollo/messaging/helpers.py
gunicorn.conf

This pull request addresses #610, #611, #612

various fixes

---

apollo/settings.py
apollo/translations/si/LC_MESSAGES/javascript.po
apollo/translations/si/LC_MESSAGES/messages.po
apollo/translations/ta/LC_MESSAGES/javascript.po
apollo/translations/ta/LC_MESSAGES/messages.po

This PR merges the updated string translations in Sinhala. It also adds the template for Tamil.

updated translations for Sinhala

---

apollo/submissions/views_submissions.py

this commit fixes the issue caused by the signature change of the
QA filter factory function

fix: update call of QA filter factory

---

apollo/frontend/dashboard.py
apollo/frontend/templates/frontend/dashboard.html
apollo/frontend/views_dashboard.py
apollo/submissions/models.py
apollo/templates/admin/form_list.html

fix: equally update participant_updated for the master submission
fix: do not make form list responsive to prevent scrolling ui

refactor daily progress chart into a table

---

apollo/frontend/dashboard.py
apollo/frontend/template_filters.py
apollo/frontend/templates/frontend/dashboard.html

* now displaying a date for the daily progress labels
* sorting the labels in the expanded display by location code
* internationalization of the date labels

improve daily progress table

---

apollo/process_analysis/templates/process_analysis/checklist_summary_breakdown.html

fix: render 0% for missing histogram values

---

apollo/participants/filters.py

this pull request restores the ability to search for participants by name. prior to this, attempting to search for a participant by their name would result in a server error.

fix: restore participant name search

---

apollo/submissions/views_submissions.py

this commit addresses nditech/apollo-issues#63, which occurs when a
checklist filtered by a sample is exported.

fix: fix errors when exporting filtered checklist

---

apollo/participants/views_participants.py

this is a workaround for the wrong reporting of participant counts in the participant lists.

fix: set the pagination total

---

apollo/submissions/services.py

resolves nditech/apollo-issues#68

check for TypeError exception when dealing with multiselect fields
